# Generated by Django 5.2.7 on 2025-10-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('category', models.CharField(choices=[('abarrote', 'Abarrote'), ('bebida', 'Bebida'), ('limpieza', 'Limpieza')], default='abarrote', max_length=50, verbose_name='Categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Código de barra')),
            ],
        ),
    ]
