# Generated by Django 5.2.7 on 2025-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Limpieza', 'Limpieza'), ('Bebidas', 'Bebidas'), ('Abarrote', 'Abarrote'), ('Sabritas', 'Sabritas'), ('Galletas', 'Galletas'), ('Dulces', 'Dulces'), ('Papeleria', 'Papeleria'), ('Vitrina', 'Vitrina'), ('Cuidado Personal', 'Cuidado_personal'), ('Lacteos', 'Lacteos')], default='abarrote', max_length=50, verbose_name='Categoría'),
        ),
    ]
