# Generated by Django 5.2.7 on 2025-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_products_barcode_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True, verbose_name='Código de barra'),
            preserve_default=False,
        ),
    ]
